name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.1
        with:
          working-directory: ESPerimentinoPID/docs/

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: ESPerimentinoPID/docs/html
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
